apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    cluster.open-cluster-management.io/cloudconnection: ''
    cluster.open-cluster-management.io/provider: vmw
data:
  metadata: {{- template "metadata.vsphere" . }} 
type: Opaque