name: aws-cluster-sp2 
cluster: aws-cluster-sp2
namespace: aws-cluster-sp2
type: aws

provider:
    region: ap-southeast-1
    baseDomain: ibmsbaasonaws.com 
    aws_access_key_id: AKIASOHYVAR6AQ4QEM5A
    aws_secret_access_key: 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
    pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMmM2OTU5NWNjZWI2NDg2ZTliY2I5MmExOGUyNjQ4ZWI6VUpDSFNGUVZITlNLSFBIU1UxMVJNRjFYOTdJSkpGVDFVV09RUlpLVUdEMlBZUEFKWEM0TkRZVVQ3STFUTzkyUQ==","email":"nick.merrett@ibm.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMmM2OTU5NWNjZWI2NDg2ZTliY2I5MmExOGUyNjQ4ZWI6VUpDSFNGUVZITlNLSFBIU1UxMVJNRjFYOTdJSkpGVDFVV09RUlpLVUdEMlBZUEFKWEM0TkRZVVQ3STFUTzkyUQ==","email":"nick.merrett@ibm.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTllYzIwZDVhLTFkNmYtNDRmMS04M2E1LTM3ZjQ3OGJiMGQ5NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlNR0poTnpZd1l6ZGxabVUwTVdSallUVmxORE14WXpnMk56RmhORFZqWWlKOS5UTjZpdHVxcHpGNWpoOUI0SlIzVms2ckVrMDFHbzFlVGFhaHh6U29vQnBrbEZ4RTJBSXBvVTNkdlAxQXpCYXNNLTJPS0YwQmtaUGMwUGRsRlo1WlhObnBzOWdENDJ3ZXEwdno5eWFLMS1FTE93S2JUMnVrUmVGM1ZjSFp4aGRmWVVJZkRCYUtWY1daYnpIQ01zVnkwX18wTmlvdjZVM2IzdnZ1Skc4OURzd2JZeUVFM241Z0dReDBZMlVPWHcxZUNYTXhOX3pXX05HME1XTzl3NnREUGp1eDVsYW13RXRlUlcxVmdUOWU1TWJGSHpnX21XS1JwVDB5eW1SaGRHbzVVc2tHRExJbU9ZTnU0SXJRd2RzWjNZYndCUFhwU1VJV1hmSGo3UEFROHBkWHl0M2dSaHRJd3ppT1k3Ymx2M0hndGlJU2hrcG95OWdXakcydU4zVzA4UTVQT21Sd0J2cGY3dWdVWUZiTk1RS3JXNmtPc1dhNnRneUE5ZjZfTDU3ZmdtX09sVEJ1dnpmU1dkRERKcXduY2ZyOUtHSlVURUVHTmJaUTJuNGRtWHRWUFlGUVlNN2VYLWpRM25fTGRGU0N5MXZucVhSaE5MR2hNNnFBTTVnM1B1Zk9BTHFKXy1MT3FFYVRtaV9RUExXaGJVZHBhODlTQkxjcVYyTEhoejZTV20taUFBTzN0WjNUdjY3YmRyd3RZakpiZmRQN1doeFpXYmRVOE1Sb0JfZUZPc3RyM2ZZYk5uSk1LNmlNWGZPZy1hbWw0Z1pMWklqMkczUmROYzVZaGZ6WVk1bC1WUk9EYjh1ODJ1SGp0M2theS02ODVBMWZ3WXhJWTJSMllxa24yOUw5OHpJRDhURlBBTnJWYnNXb3c3QVBmV21QWGxEdlhnTFRaYWkwMC0tYw==","email":"nick.merrett@ibm.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTllYzIwZDVhLTFkNmYtNDRmMS04M2E1LTM3ZjQ3OGJiMGQ5NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmlNR0poTnpZd1l6ZGxabVUwTVdSallUVmxORE14WXpnMk56RmhORFZqWWlKOS5UTjZpdHVxcHpGNWpoOUI0SlIzVms2ckVrMDFHbzFlVGFhaHh6U29vQnBrbEZ4RTJBSXBvVTNkdlAxQXpCYXNNLTJPS0YwQmtaUGMwUGRsRlo1WlhObnBzOWdENDJ3ZXEwdno5eWFLMS1FTE93S2JUMnVrUmVGM1ZjSFp4aGRmWVVJZkRCYUtWY1daYnpIQ01zVnkwX18wTmlvdjZVM2IzdnZ1Skc4OURzd2JZeUVFM241Z0dReDBZMlVPWHcxZUNYTXhOX3pXX05HME1XTzl3NnREUGp1eDVsYW13RXRlUlcxVmdUOWU1TWJGSHpnX21XS1JwVDB5eW1SaGRHbzVVc2tHRExJbU9ZTnU0SXJRd2RzWjNZYndCUFhwU1VJV1hmSGo3UEFROHBkWHl0M2dSaHRJd3ppT1k3Ymx2M0hndGlJU2hrcG95OWdXakcydU4zVzA4UTVQT21Sd0J2cGY3dWdVWUZiTk1RS3JXNmtPc1dhNnRneUE5ZjZfTDU3ZmdtX09sVEJ1dnpmU1dkRERKcXduY2ZyOUtHSlVURUVHTmJaUTJuNGRtWHRWUFlGUVlNN2VYLWpRM25fTGRGU0N5MXZucVhSaE5MR2hNNnFBTTVnM1B1Zk9BTHFKXy1MT3FFYVRtaV9RUExXaGJVZHBhODlTQkxjcVYyTEhoejZTV20taUFBTzN0WjNUdjY3YmRyd3RZakpiZmRQN1doeFpXYmRVOE1Sb0JfZUZPc3RyM2ZZYk5uSk1LNmlNWGZPZy1hbWw0Z1pMWklqMkczUmROYzVZaGZ6WVk1bC1WUk9EYjh1ODJ1SGp0M2theS02ODVBMWZ3WXhJWTJSMllxa24yOUw5OHpJRDhURlBBTnJWYnNXb3c3QVBmV21QWGxEdlhnTFRaYWkwMC0tYw==","email":"nick.merrett@ibm.com"}}}'
    sshPrivatekey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAgEAsEz3nzB3JP6ntEZ2FsPF11HvmIsJVrYX6Fn80V+8A8SRGhjPSw6f
        fihPonAzZYH5fAIYHcv94SL5kt8VQustVgX/3iyYHepnrKVRpjY4M2Rhh0kHjTrT7R96pJ
        QV/sNigrekHP3E/Ehekbwrsii6ooEVg4z38jV+PgR83Q7CoiHioogyBr5g2JBgQn6z4Vr6
        FvScjTqyeo6RqbPPASxSoVYexzgzhx7k7++ryyyUE34uaRa74C86PHzqSCJ6AjQQKAqlvn
        fdaRPW0ZcjhLrqtxiKTSWh6c313JiVEIC/WhDUCwK+Z9eKodD5IedMKKlHBNeFmQKDMSL/
        NkKgFv4lns4jYDgUnvyZYv8cxsd88YzC2vDAwBWV/Agq/wjrllyK3ovsBKaSakTfahDckw
        JlE+27t2rceGaUIaqOd3qllcHjFcT2Gcuc2WeQYPjLTU4/qdWQtrEf5ZR6vlx6lFGVceRR
        KMHeimvB7ZsKnTWiVk7u3GVz5l0yl/XEiqykViOyomysyqmdTvYIpzWL9zuPYrlm7nXo8f
        qs1btzLzLu+98FRU23gIJ7nNhlDzkk6WCbBDp8+VJcO1qFEW6u6GLWvX3snxfMFWNO9wpj
        UpINBmPj+nj/Ez8h1h9/8jaOZGpaAAy60NgHYUWyn3+EqArbA7CAUL6FqrBwe6Pw2iKsAc
        sAAAdgrc0kJ63NJCcAAAAHc3NoLXJzYQAAAgEAsEz3nzB3JP6ntEZ2FsPF11HvmIsJVrYX
        6Fn80V+8A8SRGhjPSw6ffihPonAzZYH5fAIYHcv94SL5kt8VQustVgX/3iyYHepnrKVRpj
        Y4M2Rhh0kHjTrT7R96pJQV/sNigrekHP3E/Ehekbwrsii6ooEVg4z38jV+PgR83Q7CoiHi
        oogyBr5g2JBgQn6z4Vr6FvScjTqyeo6RqbPPASxSoVYexzgzhx7k7++ryyyUE34uaRa74C
        86PHzqSCJ6AjQQKAqlvnfdaRPW0ZcjhLrqtxiKTSWh6c313JiVEIC/WhDUCwK+Z9eKodD5
        IedMKKlHBNeFmQKDMSL/NkKgFv4lns4jYDgUnvyZYv8cxsd88YzC2vDAwBWV/Agq/wjrll
        yK3ovsBKaSakTfahDckwJlE+27t2rceGaUIaqOd3qllcHjFcT2Gcuc2WeQYPjLTU4/qdWQ
        trEf5ZR6vlx6lFGVceRRKMHeimvB7ZsKnTWiVk7u3GVz5l0yl/XEiqykViOyomysyqmdTv
        YIpzWL9zuPYrlm7nXo8fqs1btzLzLu+98FRU23gIJ7nNhlDzkk6WCbBDp8+VJcO1qFEW6u
        6GLWvX3snxfMFWNO9wpjUpINBmPj+nj/Ez8h1h9/8jaOZGpaAAy60NgHYUWyn3+EqArbA7
        CAUL6FqrBwe6Pw2iKsAcsAAAADAQABAAACAHt3m59PqNEuyrIU+pSczIwsJLjW/lZMtleR
        1d2nxxt4aQo2v83X0tjeUE75dvUq3lb7fHo5p3YpMVGri89OtnRdRUEKSAoDZFHjgVf+9s
        L/FNJS0cgVn9+bwR9LWlAN84qKI5PuIStxX1F+z7c4kORHtJJpgieNUPkL2YpS0PoM8xRS
        f357i4V/LvrCkyVKuoSjEJRTvDTababEdz9iFAhLMMjiUivZ9gkW92AVuyofn08XjcHGMW
        m1LboQ8xNh9MKmGkdW2KfDLhmgWE6XPNO3ivvWVBtSk1HHRfXFxLzFtkpzxHci20LR//e/
        bXW4fzUj3rs2qDwcP1F3vXf8ysjQC2IgSuH9v+n7cWsJwIsbprQlezSi7ThL0J3+VR/JAD
        DPYHW2vy3w3dtfj0MYxoJCTtvlO8ysuyT9ha70xBD/BBhygKDL4BLBoVDZSTPdYb08HJEa
        tyU+vlpHE/k5skAU27sMf5KBCyEkGVpDV+FkgeZYPiN9KnbDRhNDv8webZwZAxD7nogPKK
        d+7aXKCQVb32a5tUU83EUgd6iH3YhcI7nuBmxnD5NeW/yQVV+0VXOh6udwdalNcuqH0HNI
        bos1ZtXhPIvfBI8WYYAHb6uU/HD7WSflo1oifL3iU9YTxZPVXyZimbKAtwdwiKfboUJS6J
        SClR1MM9kNgq9CysWZAAABAQCUeobC+1uXJf5YyRQdU/c2zS4l477o5cNSrAcjaaU+L7SL
        9Yvaw3LqmIKVlotuRsKlr3hqTVn66oHAQsHXLlaK/sUDxi46x6nvARsh4vFrap+wqcXT8R
        AquhVUPcngM0/C4eIU+1czqt+oCYHL6pSrhyKksOQkQ8/5OkAKUHysWVflFm5TpidkPzEA
        2+4UHRI2yRn7TSp3dqpwt3efIwnMGUk0fub0jhK52EnWeXgtxTyLe0QFX1V7CBLbogl+Bb
        XVpoFSHKe7uz3ShcmSzGpyqN16m4c5mhqo4ZSiiD5+Lwt4s/lOBlmaI36IzsXVHkFwwAbx
        BnZ0sPyLVq0ieRXuAAABAQDXTDaJu7jTNzZwZVZgFc8pfGX9wFt8AZCHHHVu532ZrzQ+1n
        SeexVpOD+Z9O/G0Mt4v9152jG8M+GMVZ2d3AymNXMQT9PZldTz/ELs7UvmW6Lb9C+x+lci
        aRjsxYhh1zXovjxGQvCqqf2vRnSOFm4cRT+hwaC7aNuxC8lOyTBMWX4lJzc3YTi9Jp8cMT
        GXdiHId9x2zgppnG0t/bdFlyyje08lw5VLpB+JAEnCWUS3IY7vplTFSbpFhM7ch3m4na9/
        cneHY9+dtKvY/y6z0WAo5cIbtWynOXxIWBqKjb/2tU7cH7OaW/FHK65UbjSzMCc45CvgQ8
        icMY0+OWw63iTVAAABAQDRoWjVadkffqfC7sz7U3ONsdnjUKfPgBDOCnBfunKyBlGrDlER
        vb0Pe29xD7n9VCI2Lwlsh2ZQ6RtLv8dWHQeTmqE2jFz0y3A5v57tVDfz2Uf5D3L+Ud8cah
        HKxHegiudm2dshGybOMpSzrf2w6/11PIY/Fts1KCkrRvBxhc9Es16NQklajfJv9uIOSw4+
        AV+RpUpnOtCehp3noRd65jZxvKx1jx25JfRLTDDZj26BDUukPCTWFugHdnOmkYwwOm3E52
        GWrI2W+H65x5Dmxi7HusfB28p2+yS8arNLL61Lacs0Xvcw8N5B8/rTZPuD1i2MpksJGKL7
        eAXxxMRS5VwfAAAAI25pY2ttZXJyZXR0QE5pY2tzLU1hY0Jvb2stUHJvLmxvY2FsAQIDBA
        UGBw==
        -----END OPENSSH PRIVATE KEY-----
    sshPublickey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCwTPefMHck/qe0RnYWw8XXUe+YiwlWthfoWfzRX7wDxJEaGM9LDp9+KE+icDNlgfl8Ahgdy/3hIvmS3xVC6y1WBf/eLJgd6mespVGmNjgzZGGHSQeNOtPtH3qklBX+w2KCt6Qc/cT8SF6RvCuyKLqigRWDjPfyNX4+BHzdDsKiIeKiiDIGvmDYkGBCfrPhWvoW9JyNOrJ6jpGps88BLFKhVh7HODOHHuTv76vLLJQTfi5pFrvgLzo8fOpIInoCNBAoCqW+d91pE9bRlyOEuuq3GIpNJaHpzfXcmJUQgL9aENQLAr5n14qh0Pkh50woqUcE14WZAoMxIv82QqAW/iWeziNgOBSe/Jli/xzGx3zxjMLa8MDAFZX8CCr/COuWXIrei+wEppJqRN9qENyTAmUT7bu3atx4ZpQhqo53eqWVweMVxPYZy5zZZ5Bg+MtNTj+p1ZC2sR/llHq+XHqUUZVx5FEowd6Ka8HtmwqdNaJWTu7cZXPmXTKX9cSKrKRWI7KibKzKqZ1O9ginNYv3O49iuWbudejx+qzVu3MvMu773wVFTbeAgnuc2GUPOSTpYJsEOnz5Ulw7WoURbq7oYta9feyfF8wVY073CmNSkg0GY+P6eP8TPyHWH3/yNo5kaloADLrQ2AdhRbKff4SoCtsDsIBQvoWqsHB7o/DaIqwByw== nickmerrett@Nicks-MacBook-Pro.local'

masters:
    count: 3
    diskIops: 4000
    diskSize: 100
    diskType: io1
    machineType: m5.xlarge

workers:
    count: 3
    diskIops: 4000
    diskSize: 100
    diskType: io1
    machineType: m5.xlarge

network:
    networkName: 'VM Network'
    apiVIP: 10.20.20.2
    ingressVIP: 10.20.20.3
    
