apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Azure
    region: {{ .Values.region }}
    name: '{{ .Values.cluster }}'
    cluster.open-cluster-management.io/clusterset: all-openshift-clusters
    vendor: OpenShift
  name: '{{ .Values.cluster }}'
spec:
  hubAcceptsClient: true
