apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster }}-install-config
  namespace: '{{ .Values.cluster }}'
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ include "install-config.azure.tpl" . | b64enc}} 

