apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{.Values.cluster }}-worker
  namespace: '{{ .Values.cluster }}'
spec:
  clusterDeploymentRef:
    name: '{{ .Values.cluster }}'
  name: worker
  platform:
    azure:
      osDisk:
        diskSizeGB: 128
      type: Standard_D2s_v3
      zones:
      - "1"
      - "2"
      - "3"
  replicas: 3
